export interface Project {
  id: string;
  title: string;
  tagline: string;
  description: string;
  technologies: string[];
  highlight: string;
  category: 'AI / NLP' | 'Backend' | 'Full-Stack' | 'Cloud & Systems';
  purpose: string;
  keyFeatures: string[];
  illustrationType: 'nlp' | 'deadline' | 'library' | 'cloud-edge';
}

export interface SkillCategory {
  title: string;
  skills: string[];
}

export const PERSONAL_INFO = {
  name: 'Sadhana Sankar',
  initials: 'SS',
  tagline: 'Build. Learn. Explore.',
  role: 'Computer Science Engineering Student | Developer | AI & Cloud Enthusiast',
  heroSupportingText: 'Computer Science Engineering Student & Aspiring Developer',
  heroDescription:
    'I build practical software solutions while exploring AI, cloud computing, web development, and modern technologies.',
  shortIntro:
    'I am Sadhana Sankar, a Computer Science Engineering student passionate about software development, artificial intelligence, cloud computing, and building practical technology solutions. I enjoy learning new technologies, solving problems, and turning ideas into useful applications.',
  aboutText: [
    'I am a Computer Science Engineering student at VIT with an interest in software development and emerging technologies. My academic journey has allowed me to explore areas such as artificial intelligence, cloud computing, web development, databases, distributed systems, and blockchain.',
    'I enjoy working on projects that combine technical concepts with real-world problems. I am continuously improving my programming, problem-solving, and development skills through academic projects and hands-on experimentation.'
  ],
  location: 'Vellore, Tamil Nadu, India',
  institution: 'Vellore Institute of Technology (VIT)',
  degree: 'M.Tech Integrated Computer Science and Engineering',
  timeline: '2024 – 2029',
  interests: [
    { label: 'Computer Science', focus: 'Algorithms, Data Structures & Systems' },
    { label: 'AI & ML', focus: 'NLP, Intelligent Systems & Verification' },
    { label: 'Cloud Computing', focus: 'Distributed Systems, AWS Concepts & Edge' },
    { label: 'Full-Stack Development', focus: 'Spring Boot, Java, Web Architecture' },
  ],
  heroBadges: ['CSE', 'AI', 'Cloud', 'Web Development'],
};

export const SKILL_CATEGORIES: SkillCategory[] = [
  {
    title: 'Programming',
    skills: ['C', 'C++', 'Java', 'Python'],
  },
  {
    title: 'Web Development',
    skills: ['HTML', 'CSS', 'JavaScript', 'Bootstrap', 'Angular', 'Node.js'],
  },
  {
    title: 'Backend & Database',
    skills: ['Spring Boot', 'Hibernate / JPA', 'MySQL'],
  },
  {
    title: 'AI & Data',
    skills: ['Artificial Intelligence', 'Machine Learning', 'NLP', 'Data Mining'],
  },
  {
    title: 'Cloud & Distributed Systems',
    skills: ['Cloud Computing', 'Hadoop', 'HDFS', 'MapReduce', 'AWS concepts'],
  },
  {
    title: 'Tools & Technologies',
    skills: ['Git', 'GitHub', 'Docker', 'Streamlit', 'VS Code', 'NetBeans', 'Eclipse'],
  },
];

export const PROJECTS: Project[] = [
  {
    id: 'evidence-guard',
    title: 'EvidenceGuard — LLM Hallucination Detection & Evidence Verification',
    tagline: 'Automated claim fact-checking & hallucination reduction pipeline',
    description:
      'An AI-based project focused on detecting potentially hallucinated claims generated by language models and verifying claims against supporting evidence.',
    technologies: ['Python', 'NLP', 'NLI', 'Streamlit', 'AI'],
    highlight: 'AI / Research Project',
    category: 'AI / NLP',
    purpose:
      'To provide systematic verification for generated text by extracting atomic factual assertions and cross-referencing with ground-truth documentary sources.',
    keyFeatures: [
      'Deconstructs generative model outputs into discrete factual propositions',
      'Applies Natural Language Inference (NLI) to assess premise-hypothesis entailment',
      'Interactive Streamlit interface for live prompt verification and evidence audit',
      'Designed to reduce hallucinations in academic and informational question-answering'
    ],
    illustrationType: 'nlp',
  },
  {
    id: 'smart-deadline',
    title: 'Smart Deadline Collision Detector',
    tagline: 'Intelligent conflict resolution and schedule coordination service',
    description:
      'A server-side application concept designed to identify conflicting deadlines and help users organize tasks more effectively.',
    technologies: ['Java', 'Spring Boot', 'Server-Side Development', 'Database'],
    highlight: 'Web / Backend Project',
    category: 'Backend',
    purpose:
      'To resolve calendar bottlenecks and cognitive overload by proactively calculating overlapping deliverables and resource constraints.',
    keyFeatures: [
      'Server-side temporal interval algorithms to detect hard and soft task overlaps',
      'Structured task priority weighting to highlight critical dependency bottlenecks',
      'RESTful endpoints for calendar sync, deadline tracking, and notification triggers',
      'Relational schema modeling for multi-course and multi-project task streams'
    ],
    illustrationType: 'deadline',
  },
  {
    id: 'library-management',
    title: 'Library Management System',
    tagline: 'Robust cataloging, member lifecycle, and transactional inventory engine',
    description:
      'A web-based library management application designed to manage users, books, and library-related operations through a structured backend system.',
    technologies: ['Java', 'Spring Boot', 'MySQL', 'REST API'],
    highlight: 'Full-Stack / Backend Project',
    category: 'Full-Stack',
    purpose:
      'To modernize academic library operations with structured data persistence, book checkout lifecycle tracking, and authenticated administrative control.',
    keyFeatures: [
      'Comprehensive CRUD architecture for books, members, categories, and circulation records',
      'Relational database architecture normalized in MySQL with JPA/Hibernate mapping',
      'API endpoints for searching, issuing, returning, and tracking overdue item states',
      'Clean separation of concerns adhering to standard Service-Repository patterns'
    ],
    illustrationType: 'library',
  },
  {
    id: 'cloud-edge-emergency',
    title: 'Cloud Edge Emergency Communication System',
    tagline: 'Decentralized disaster communication architecture bridging edge and cloud',
    description:
      'A disaster-response concept that combines cloud and edge technologies to support emergency communication when conventional internet connectivity is unavailable or unreliable.',
    technologies: ['Cloud Computing', 'Edge Computing', 'Distributed Systems'],
    highlight: 'Cloud / Research Concept',
    category: 'Cloud & Systems',
    purpose:
      'To maintain vital communication channels and rescue status coordination during critical natural disasters or telecommunication blackouts.',
    keyFeatures: [
      'Hybrid edge-cloud hierarchy deploying localized mesh micro-nodes in disaster zones',
      'Store-and-forward asynchronous synchronization when cloud uplinks become intermittent',
      'Prioritized emergency payload routing for vital medical and survivor telemetry',
      'Fault-tolerant decentralized topology ensuring local survival without central servers'
    ],
    illustrationType: 'cloud-edge',
  },
];

export const EDUCATION_DATA = {
  institution: 'Vellore Institute of Technology',
  location: 'Vellore, Tamil Nadu, India',
  degree: 'M.Tech Integrated Computer Science and Engineering',
  timeline: '2024 – 2029',
  description:
    'Integrated computer science program with coursework and hands-on learning across programming, software engineering, artificial intelligence, cloud computing, databases, distributed systems, and emerging technologies.',
  courseworkAreas: [
    'Data Structures & Algorithms',
    'Object-Oriented Programming (Java / C++)',
    'Database Management Systems & SQL',
    'Artificial Intelligence & Machine Learning',
    'Cloud Computing & Distributed Systems',
    'Operating Systems & Computer Networks',
    'Web Architecture & Enterprise Frameworks',
    'Blockchain & Emerging Technologies',
  ],
};

export const CERTIFICATES = [
  {
    id: '01',
    code: 'Certificate 01',
    category: 'Technical Learning',
    note: 'Certificate details to be added',
    status: 'In Progress / Academic Track',
  },
  {
    id: '02',
    code: 'Certificate 02',
    category: 'Programming / Development',
    note: 'Certificate details to be added',
    status: 'In Progress / Academic Track',
  },
  {
    id: '03',
    code: 'Certificate 03',
    category: 'AI / Data',
    note: 'Certificate details to be added',
    status: 'In Progress / Academic Track',
  },
  {
    id: '04',
    code: 'Certificate 04',
    category: 'Cloud / Technology',
    note: 'Certificate details to be added',
    status: 'In Progress / Academic Track',
  },
];

export const FUN_FACTS = [
  {
    title: 'Curious Learner',
    description: 'I enjoy exploring new technologies and understanding how things work.',
    icon: 'compass',
  },
  {
    title: 'Problem Solver',
    description: 'I like breaking complex problems into smaller, manageable steps.',
    icon: 'puzzle',
  },
  {
    title: 'Project Explorer',
    description: 'I enjoy turning academic concepts into practical project ideas.',
    icon: 'rocket',
  },
  {
    title: 'Always Learning',
    description: 'There is always another technology, framework, or concept to explore.',
    icon: 'sparkles',
  },
];
